name = "Maranatha"
uuid = "f59da73d-25b7-4e5f-93e8-d831d7277eb4"
version = "0.1.0"
authors = ["Benjamin J. Choi <benchoi@ccs.tsukuba.ac.jp>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TaylorSeries = "6aa5eb33-94cf-58f4-a9d0-e4b2c4fc25ea"

[compat]
Dates = "1.11.0"
Enzyme = "0.13.129"
LinearAlgebra = "1.12.0"
Printf = "1.11.0"
SpecialFunctions = "2.7.1"
Statistics = "1.11.1"
TaylorSeries = "0.20.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
